import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "./components/Header";
import { SmoothScroll } from "./components/SmoothScroll"; // Import wrapper

// 1. Configuration de TAN Memories (Titres)
const tanMemories = localFont({
  src: [
    {
      path: "./fonts/TAN-MEMORIES-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/TAN-MEMORIES-Italic.ttf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-tan-custom",
  display: "swap",
});

// 2. Configuration d'Helvetica Neue (Texte courant)
const helveticaNeue = localFont({
  src: [
    {
      path: "./fonts/HelveticaNeueLTW0545Light.otf",
      weight: "300", // Light
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueLTW0555Roman.otf",
      weight: "400", // Regular/Roman
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueLTW0585Heavy.otf",
      weight: "800", // Heavy/Bold
      style: "normal",
    },
  ],
  variable: "--font-helvetica-custom",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${tanMemories.variable} ${helveticaNeue.variable} antialiased`}
    >
      {/* Removed scroll-behavior: smooth and h-full from html to let Lenis breathe */}
      <body className="flex flex-col">
        <SmoothScroll>
          <Header />
          <main>{children}</main>
        </SmoothScroll>
      </body>
    </html>
  );
}
